### ISSUE TITLE
Latest Update from University of Illinois Police

### ISSUE THREAD

**Issue by explor3r** [Zhenyao-Sun/zhenyao-sun.github.io#1]
Sunday, June 11, 2017 at 10:06pm (CDT)
[https://www.facebook.com/UIpolice/posts/10155390416741060](https://www.facebook.com/UIpolice/posts/10155390416741060)

**Comment by explor3r** [comment]
我根据目前为止能够收集到的来源可靠的信息绘制了一幅事发当天的路线图。
介于没有渠道联系到家属，也不希望未经家属同意私自发布相关信息，所以在此发出，望转达。
因为本人不在Illinois，如过发现图中标注存在不准确之处我可以及时修改。
在此希望尽微薄之力，愿早日找到章莹颖！

路线图如下：
![yingying zhang 2](https://user-images.githubusercontent.com/3682816/27023724-a58824cc-4f08-11e7-9260-38d75a300a33.png)

**Comment by ZhangQixiangChina** [comment]
谢谢,我们大家都很担心,焦急

**Comment by explor3r** [comment]
我们这边的同学们也都时刻关注着相关的消息，替她担心。。
想来想去真的不知道可以做些什么，但愿这个路线图能够提供些许帮助吧。。
愿她能够平安归来 :pray:

**Comment by ZhangQixiangChina** [comment]
我把这个图和网址发到了我们高中同学群里,大家都在想办法。希望能够帮助得到她.
